global:
  temporal:
    host: "localhost:7233"
  storage:
    connectionString: s3://commander/workflows/?credential=hmac:5kpWVH8bjA3ak8Kv:ipvdKs21pyp3aFmKwNbU9iAJJTkH3c9Q&endpoint=http://localhost:9099&location=&force_path_style=true
    #connectionString: minio://commander/workflows?credential=hmac:5kpWVH8bjA3ak8Kv:ipvdKs21pyp3aFmKwNbU9iAJJTkH3c9Q&endpoint=http://localhost:9099
    