global:
  temporal:
    host: "localhost:7233"
  storage:
    connectionString: s3://commander/workflows/?accessKey=5kpWVH8bjA3ak8Kv&secretKey=ipvdKs21pyp3aFmKwNbU9iAJJTkH3c9Q&endpoint=http://localhost:9099
    